[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi[standard]>=0.136.3",
    "geopy>=2.4.1",
    "h3>=4.5.0",
    "pandas>=3.0.3",
    "psycopg2-binary>=2.9.12",
    "pydantic-extra-types>=2.11.1",
    "pydantic-settings>=2.14.1",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "selenium>=4.44.0",
    "sentry-sdk>=2.61.1",
    "sqlalchemy>=2.0.50",
    "timezonefinder>=8.2.4",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
