export const GROUP_MATCHES = [
  { id: 1, group: "A", h: "Mexico", a: "South Africa" },
  { id: 2, group: "A", h: "South Korea", a: "Czechia" },
  { id: 3, group: "B", h: "Canada", a: "Bosnia and Herzegovina" },
  { id: 4, group: "D", h: "United States", a: "Paraguay" },
  { id: 5, group: "C", h: "Haiti", a: "Scotland" },
  { id: 6, group: "D", h: "Australia", a: "Turkey" },
  { id: 7, group: "C", h: "Brazil", a: "Morocco" },
  { id: 8, group: "B", h: "Qatar", a: "Switzerland" },
  { id: 9, group: "E", h: "Ivory Coast", a: "Ecuador" },
  { id: 10, group: "E", h: "Germany", a: "Curacao" },
  { id: 11, group: "F", h: "Netherlands", a: "Japan" },
  { id: 12, group: "F", h: "Sweden", a: "Tunisia" },
  { id: 13, group: "H", h: "Saudi Arabia", a: "Uruguay" },
  { id: 14, group: "H", h: "Spain", a: "Cape Verde" },
  { id: 15, group: "G", h: "Iran", a: "New Zealand" },
  { id: 16, group: "G", h: "Belgium", a: "Egypt" },
  { id: 17, group: "I", h: "France", a: "Senegal" },
  { id: 18, group: "I", h: "Iraq", a: "Norway" },
  { id: 19, group: "J", h: "Argentina", a: "Algeria" },
  { id: 20, group: "J", h: "Austria", a: "Jordan" },
  { id: 21, group: "L", h: "Ghana", a: "Panama" },
  { id: 22, group: "L", h: "England", a: "Croatia" },
  { id: 23, group: "K", h: "Portugal", a: "DR Congo" },
  { id: 24, group: "K", h: "Uzbekistan", a: "Colombia" },
  { id: 25, group: "A", h: "Czechia", a: "South Africa" },
  { id: 26, group: "B", h: "Switzerland", a: "Bosnia and Herzegovina" },
  { id: 27, group: "B", h: "Canada", a: "Qatar" },
  { id: 28, group: "A", h: "Mexico", a: "South Korea" },
  { id: 29, group: "C", h: "Brazil", a: "Haiti" },
  { id: 30, group: "C", h: "Scotland", a: "Morocco" },
  { id: 31, group: "D", h: "Turkey", a: "Paraguay" },
  { id: 32, group: "D", h: "United States", a: "Australia" },
  { id: 33, group: "E", h: "Germany", a: "Ivory Coast" },
  { id: 34, group: "E", h: "Ecuador", a: "Curacao" },
  { id: 35, group: "F", h: "Netherlands", a: "Sweden" },
  { id: 36, group: "F", h: "Tunisia", a: "Japan" },
  { id: 37, group: "H", h: "Uruguay", a: "Cape Verde" },
  { id: 38, group: "H", h: "Spain", a: "Saudi Arabia" },
  { id: 39, group: "G", h: "Belgium", a: "Iran" },
  { id: 40, group: "G", h: "New Zealand", a: "Egypt" },
  { id: 41, group: "I", h: "Norway", a: "Senegal" },
  { id: 42, group: "I", h: "France", a: "Iraq" },
  { id: 43, group: "J", h: "Argentina", a: "Austria" },
  { id: 44, group: "J", h: "Jordan", a: "Algeria" },
  { id: 45, group: "L", h: "England", a: "Ghana" },
  { id: 46, group: "L", h: "Panama", a: "Croatia" },
  { id: 47, group: "K", h: "Portugal", a: "Uzbekistan" },
  { id: 48, group: "K", h: "Colombia", a: "DR Congo" },
  { id: 49, group: "C", h: "Scotland", a: "Brazil" },
  { id: 50, group: "C", h: "Morocco", a: "Haiti" },
  { id: 51, group: "B", h: "Switzerland", a: "Canada" },
  { id: 52, group: "B", h: "Bosnia and Herzegovina", a: "Qatar" },
  { id: 53, group: "A", h: "Czechia", a: "Mexico" },
  { id: 54, group: "A", h: "South Africa", a: "South Korea" },
  { id: 55, group: "E", h: "Curacao", a: "Ivory Coast" },
  { id: 56, group: "E", h: "Ecuador", a: "Germany" },
  { id: 57, group: "F", h: "Japan", a: "Sweden" },
  { id: 58, group: "F", h: "Tunisia", a: "Netherlands" },
  { id: 59, group: "D", h: "Turkey", a: "United States" },
  { id: 60, group: "D", h: "Paraguay", a: "Australia" },
  { id: 61, group: "I", h: "Norway", a: "France" },
  { id: 62, group: "I", h: "Senegal", a: "Iraq" },
  { id: 63, group: "G", h: "Egypt", a: "Iran" },
  { id: 64, group: "G", h: "New Zealand", a: "Belgium" },
  { id: 65, group: "H", h: "Cape Verde", a: "Saudi Arabia" },
  { id: 66, group: "H", h: "Uruguay", a: "Spain" },
  { id: 67, group: "L", h: "Panama", a: "England" },
  { id: 68, group: "L", h: "Croatia", a: "Ghana" },
  { id: 69, group: "J", h: "Algeria", a: "Austria" },
  { id: 70, group: "J", h: "Jordan", a: "Argentina" },
  { id: 71, group: "K", h: "Colombia", a: "Portugal" },
  { id: 72, group: "K", h: "DR Congo", a: "Uzbekistan" },
];

export const KNOCKOUT_MATCH_IDS = {
  R32: [73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88],
  R16: [89,90,91,92,93,94,95,96],
  QF: [97,98,99,100],
  SF: [101, 102],
  THIRD: 103,
  FINAL: 104,
};
